In [105]:
#Start
import pandas as pd
import numpy as np

R = pd.read_csv('mouse.csv',header=None)
matrix = np.matrix(R);matrix

matrix([[-100,   -1,   -1,   -1],
        [  -1, -100,   -1, -100],
        [  -1,   -1,   -1,   -1],
        [  -1, -100,   -1, -100],
        [  -1,   -1,   -1,   -1],
        [  -1,   -1,   -1,   -1],
        [  -1,   -1, -100,   -1],
        [-100,   -1,   -1,   -1],
        [  -1,   -1,  100,   -1],
        [  -1, -100,   -1,   -1],
        [  -1,   -1,   -1, -100]], dtype=int64)

In [106]:
matrix.shape

(11, 4)

# Goal Cell

In [108]:
#the goal is 100, each step costs -1 and -100 implies a cat or a mouse trap.
num_rows, num_cols = matrix.shape
shape=[num_rows, num_cols]

m=list(range(0,num_rows))
n=list(range(0,num_cols))


for i in m:
    for j in n:
        if matrix[i,j]==100:
            print('goal cell is:',i,'x',j,'value is:',matrix[i,j])
      


goal cell is: 8 x 2 value is: 100


In [109]:
for k in combinations:
    i, j = k
    if matrix[i,j] == 100:
        print(k)


# Define moves, Path and All paths

In [110]:
def is_valid_move(matrix, visited, row, col):
    num_rows, num_cols = matrix.shape  #length of rows and cols
    if row < 0 or row >= num_rows or col < 0 or col >= num_cols: #moves are not to be out of bound
        return False
    else:
        return matrix[row, col] != -100 and not visited[row, col]  #to ensure that the next state is not 
    #trap or already visited


In [111]:
def find_paths(matrix, visited, row, col, path, paths):
    num_rows, num_cols = matrix.shape
    visited[row, col] = True #to mark a cell(i,j) that is already visited.
    path.append((row, col))#if state is visited, add the index to the path
    
    if matrix[row, col] == 100: #if end goal of 100 is reached
        paths.append(path.copy())
    else:
        moves = [(row-1, col), (row+1, col), (row, col-1), (row, col+1)] #try to move in all possible directions
        #directions: up, down, left, right.
        
        for move in moves:
            next_row, next_col = move #based on previous action
            if is_valid_move(matrix, visited, next_row, next_col):
                find_paths(matrix, visited, next_row, next_col, path, paths)
    
    visited[row, col] = False #mark current cell as unvisited and remove from the path (to  backtrack)
    path.pop() #.pop() results the last value in list.




In [112]:
def find_all_paths(matrix, start_row, start_col):
    num_rows, num_cols = matrix.shape
    visited = np.zeros_like(matrix, dtype=bool) # a m*n array with zeros for to track the visited cells.
    
    paths = [] 
    find_paths(matrix, visited, start_row, start_col, [], paths)
    return paths



# Test

In [113]:

start_row, start_col = 1, 0  # starting position: change it accordingly
paths = find_all_paths(matrix, start_row, start_col)
print('all paths:')

for path in paths:
    print(path)

all paths:
[(1, 0), (2, 0), (3, 0), (4, 0), (5, 0), (6, 0), (6, 1), (5, 1), (4, 1), (4, 2), (5, 2), (5, 3), (6, 3), (7, 3), (8, 3), (9, 3), (9, 2), (8, 2)]
[(1, 0), (2, 0), (3, 0), (4, 0), (5, 0), (6, 0), (6, 1), (5, 1), (4, 1), (4, 2), (5, 2), (5, 3), (6, 3), (7, 3), (8, 3), (9, 3), (9, 2), (10, 2), (10, 1), (10, 0), (9, 0), (8, 0), (8, 1), (7, 1), (7, 2), (8, 2)]
[(1, 0), (2, 0), (3, 0), (4, 0), (5, 0), (6, 0), (6, 1), (5, 1), (4, 1), (4, 2), (5, 2), (5, 3), (6, 3), (7, 3), (8, 3), (9, 3), (9, 2), (10, 2), (10, 1), (10, 0), (9, 0), (8, 0), (8, 1), (8, 2)]
[(1, 0), (2, 0), (3, 0), (4, 0), (5, 0), (6, 0), (6, 1), (5, 1), (4, 1), (4, 2), (5, 2), (5, 3), (6, 3), (7, 3), (8, 3), (8, 2)]
[(1, 0), (2, 0), (3, 0), (4, 0), (5, 0), (6, 0), (6, 1), (5, 1), (4, 1), (4, 2), (5, 2), (5, 3), (6, 3), (7, 3), (7, 2), (8, 2)]
[(1, 0), (2, 0), (3, 0), (4, 0), (5, 0), (6, 0), (6, 1), (5, 1), (4, 1), (4, 2), (5, 2), (5, 3), (6, 3), (7, 3), (7, 2), (7, 1), (8, 1), (8, 0), (9, 0), (10, 0), (10, 1), (10, 2)

In [114]:
print(matrix)

[[-100   -1   -1   -1]
 [  -1 -100   -1 -100]
 [  -1   -1   -1   -1]
 [  -1 -100   -1 -100]
 [  -1   -1   -1   -1]
 [  -1   -1   -1   -1]
 [  -1   -1 -100   -1]
 [-100   -1   -1   -1]
 [  -1   -1  100   -1]
 [  -1 -100   -1   -1]
 [  -1   -1   -1 -100]]


In [115]:
lengths = [len(path) for path in paths]
min_length = min(lengths)   
max_length=max(lengths)
min_cost = (min_length-1)*-1+100
max_cost = (max_length-1)*-1+100
print('the max number of steps possible is ',max(lengths),'and total cost is:',max_cost)


for path in paths:
    if len(path)==min_length:
        print('minimum number of steps taken:',min_length,'and the path is:',path,'min total cost is:',min_cost)



the max number of steps possible is  28 and total cost is: 73
minimum number of steps taken: 10 and the path is: [(1, 0), (2, 0), (3, 0), (4, 0), (5, 0), (6, 0), (6, 1), (7, 1), (8, 1), (8, 2)] min total cost is: 91
minimum number of steps taken: 10 and the path is: [(1, 0), (2, 0), (3, 0), (4, 0), (5, 0), (6, 0), (6, 1), (7, 1), (7, 2), (8, 2)] min total cost is: 91
minimum number of steps taken: 10 and the path is: [(1, 0), (2, 0), (3, 0), (4, 0), (5, 0), (5, 1), (6, 1), (7, 1), (8, 1), (8, 2)] min total cost is: 91
minimum number of steps taken: 10 and the path is: [(1, 0), (2, 0), (3, 0), (4, 0), (5, 0), (5, 1), (6, 1), (7, 1), (7, 2), (8, 2)] min total cost is: 91
minimum number of steps taken: 10 and the path is: [(1, 0), (2, 0), (3, 0), (4, 0), (4, 1), (5, 1), (6, 1), (7, 1), (8, 1), (8, 2)] min total cost is: 91
minimum number of steps taken: 10 and the path is: [(1, 0), (2, 0), (3, 0), (4, 0), (4, 1), (5, 1), (6, 1), (7, 1), (7, 2), (8, 2)] min total cost is: 91


In [116]:
#end