# Definitions


1) What is Reinforcement Learning?

ans) Reinforcement learning involve the series of techniques where an agent (usually a machine), interacts with the environment  and gets a feedback. This feedback is the reward or a penatly for the chosen action along with the new state. The goal of the agent is to maximize rewards. The idea is to find out an optimal path or approach, through random actions, ( still part of the policy of the agent ), that ultimately maximizes the reward. 

2) Explain key terms:

2.a) Environment: Enviroment is the space at which the agent takes actions in. The environment grants the agent rewards or penalties for the action chosen along with the new state for the agent. If the new state granted for the agent is a terminating state, the algorithm ends.

2.b) State: State is the possible location an agent can start, end, or land at after an action. States, depending on what nature they are, can yield rewards or penalties. If the state is terminating, that is the end goal, then it rewards for the agent for completing the task. Else, states can penalize the agent, for loitering and increasing the run time. States also provide the information on the environment.

2.c) Action: Action is the movement that an agent can make. The possible movements is often declared in the policy, where the policy is the behaviour of the agent. For example, a taxi in the state-space, that is, all possible states, can move, north, south, east and west and this rule is declared in the policy. So action is the way an agent can move or transition across states.

2.d)Reward: Rewards or penalties are the necessary points, either in addition or deduction, for keeping the agent continue actions, to ultimatley find out the optimal path. Rewards are granted for correct actions/ good behaviour and penalties for the ones that are undesired.

2.e) Agent: The agent is the learner in a reinforcement problem. The agent takes decisions and learns through it, ultimatley achieving its set objective. The agent interacts with its environment and it is granted rewards/penalties and new states till it achieves its end goal. The agent's behaviour is declared in the policy and with it transitions across states to reach the end goal.

2.f) Greedy Algorithm: A greedy algorithm is one that maximizes its rewards. Such algorithm does not venture or explore to find out other possibilities or paths, and is usually restricted to one optimal path it finds first. An example would be the Q-learning algorithm, where the agent tries to maximize its Q values. The algorithm is fast at the cost of possibilities it would find if it were to follow an explorative algorithm.

2.e) Epsilon Greedy Algorithm: To solve the problem of a greedy algorithm, a random value is generated. If this random value is less than epsilon, it would follow an explorative algoritm such as a SARSA approch. If not, the algorithm sticks to being greedy. Such an algorithm helps to strike a balance between being greedy and exploitative, yielding the benefits of both. 


# Mouse-Cheese-Cat Maze

# Import libraries

In [28]:
import numpy as np
import pandas as pd

# Create a state-action-reward-matrix

In [29]:
R = pd.read_csv('mouse.csv',header=None)

In [30]:
R = np.matrix(R)
R
#zero for every empty state. 100 for the state with cheese and -100 for the state with a cat

matrix([[   0,    0,    0,    0],
        [   0, -100,    0, -100],
        [   0,    0,    0,    0],
        [   0, -100,    0,  100]], dtype=int64)

In [31]:
#Qmatrix

Q = np.zeros([4,4]);Q

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Initialize gamma and initial state

In [32]:
gamma = 0.4
initial_state = 2 # initial state 2 works and gamma 0.4

# Available actions function

In [33]:
def avl_actions(state):
    current_state_row = R[state,]
    av_act = np.where(current_state_row > -1)[1]
    return av_act

In [34]:
#available actions for current state = 2

available_act = avl_actions(initial_state)

In [35]:
available_act

array([0, 1, 2, 3], dtype=int64)

# Random action within policy

In [36]:
#random action performed in the range of all possible actions actions

def sample_next_action(available_actions_range):
    next_action = int(np.random.choice(available_actions_range,1))
    return next_action

In [37]:
action = sample_next_action(available_act)

In [38]:
action

2

# Update the Q-matrix

In [39]:
#update Q matrix based on the path taken

def update(current_state,action,gamma):
    max_index = np.where(Q[action,] == np.max(Q[action,]))[0]

    if max_index.shape[0] >1:
        max_index = int(np.random.choice(max_index, size=1))
    else:
        max_index = int(max_index)
    max_value = Q[action,max_index]
    Q[current_state,action] = R[current_state,action] + gamma*max_value

In [40]:

update(initial_state,action,gamma)

In [41]:
Q

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Iterations

In [42]:

for i in range(1500):
    current_state = np.random.randint(0,int(Q.shape[0]))
    available_act = avl_actions(current_state)
    action = sample_next_action(available_act)
    update(current_state,action,gamma)

# Final Q matrix (trained)

In [43]:
print("Q Matrix - Trained")
print((Q / np.max(Q)) * 100)

Q Matrix - Trained
[[ 16.    6.4  16.   40. ]
 [ 16.    0.   16.    0. ]
 [ 16.    6.4  16.   40. ]
 [ 16.    0.   16.  100. ]]


# Paths taken

In [46]:
current_state =1 #change it accordingly, to get different results 
steps = [current_state]

while current_state != 3:
    next_step_index = np.where(Q[current_state,] == np.max(Q[current_state,]))[0]

    if next_step_index.shape[0] > 1:
        next_step_index = int(np.random.choice(next_step_index, size=1))
    else:
        next_step_index = int(next_step_index)

    steps.append(next_step_index)
    current_state = next_step_index

print("The selected path:")
print(steps)

The selected path:
[1, 0, 3]


In [45]:
#end